### ISSUE TITLE
parameters info

### ISSUE THREAD

**Issue by ricky-lim** [fenderglass/maf2synteny#1]
Could you provide more details explanations on the parameters of the CLI (maf2synteny), please?

What does the `block_sizes` mean if supplied as a list of ints, does it refer to the length of each reference genome in the MAF file?
and the default simplification parameters, what does it mean?

Many thanks in advance. Look forward to hearing from you.

Cheers

**Comment by fenderglass** [comment]
Hi,

This module is actually a part of Ragout (https://github.com/fenderglass/Ragout) - I would recommend to use the version from that repository as it contains more recent updates (the binary will be at bin/ragout-maf2synteny after compilation).

Out recent paper (https://genome.cshlp.org/content/early/2018/10/19/gr.236273.118) describes the block_size and the other parameters and their effects on final results - I would recommend starting from there. Let me know if you have more questions.

**Comment by ricky-lim** [comment]
Thanks for the reference.

Cheers!
