### ISSUE TITLE
Compatibility with a future change in the output of SibeliaZ

### ISSUE THREAD

**Issue by iminkin** [fenderglass/maf2synteny#2]
Right now SibeliaZ's GFF output does not comply strictly with the format [spec](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). I am going to make it compliant in the next releases. The only difference that seems to matter for maf2synteny is that the ID attribute will be spelled in upper-case as in the specification (right now SibeliaZ outputs 'id' in lower-case). Please add support to the ID spelled this way. An example of the output file is [here](https://github.com/medvedevgroup/SibeliaZ/blob/develop/examples/sibeliaz_out/blocks_coords.gff).

In addition, SibeliaZ will output sizes of the input sequences as pragma (as suggested by this [issue](https://github.com/medvedevgroup/SibeliaZ/issues/35)). It should simplify the computation of the coverage and maybe some other operations.

**Comment by mikolmogorov** [comment]
Should now be fixed in release 1.1

**Comment by ghost** [comment]
Fix a bug which outputs incorrect `nucLength`, see #3 .

**Comment by mikolmogorov** [comment]
@16m thanks, merged the changes and bumped the 1.2 release
