### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by kiwijiji** [fenderglass/maf2synteny#5]
l wanna ask if some blocks are missing when construct longer synteny blocks,cause the coverage is 0.98 when sibeliaz run ,but the coverage is 0.82 when maf2synteny run. almost 5000bp lost. l wanna ask why those are missing?

**Comment by mikolmogorov** [comment]
Could be because of different minimum block sizes.

**Comment by kiwijiji** [comment]
> 

sorry，do you mean the -b parameter? l set -b 5000,but the length of some non-block regions are longer than 5000, even reach up to 32076bp.  why those regions are not included in block?

**Comment by mikolmogorov** [comment]
Perhaps these regions were not aligned, and therefor did not make it into synteny blocks. The algorithm is also not perfect and may miss some regions that are difficult to align.
