### ISSUE TITLE
coverage_report.txt contents

### ISSUE THREAD

**Issue by aminakur** [fenderglass/maf2synteny#6]
What does the first part of the 'coverage_report.txt' file represent? 
```
10	11
11	1
8	4
9	5
7	12
6	206
5	6800
4	740
2	472
3	393
--------------------------------------------------------------------------------
```
I guess the second part reflects the percentage of each sequence that is covered by synteny blocks.
```
IR.chr08	29.3488
OM.chr03	39.2092
IR.chr11	21.1779
OM.chr05	32.8766
...
```

**Comment by mikolmogorov** [comment]
The first section is the number if synteny blocks with particular multiplicity (total copy number in all input genomes). E.g. there are 393 blocks with copy number 3, 472 blocks with copy number 2 etc. Hope this helps!
